### ISSUE TITLE
OpenAI 接口 batch 的触发方式？

### ISSUE THREAD

**Issue by mamaruo** [abse4411/projz_renpy_translation#35]
我看到配置文件中有对于 openai 的批量（batch）翻译，使用实时翻译GUI时，用OpenAI接口，观察日志是能触发batch的（翻译游戏主界面时）。

但使用 `llm_translate` 命令似乎无法触发。这导致每次消息都会包含一串初始prompt，**token用量极高且速度很慢**。

我测试用的是**dev分支**的代码。

![image](https://github.com/user-attachments/assets/e6f60139-a247-499f-90dc-3b771d044fe0)

附配置文件。
```yaml
    open_ai:
      batch_separator: '@##@' # The separator add to between different texts in batch translator
      batch_max_textlen: 4096 # Max len of the final text sent to the real translator
      batch_size: 100 # how many texts are batched to send to the real translator at once
      target_lang: 'Chinese'
      user_role: &user_role 'user'
      assistant_role: &assistant_role 'assistant'
      max_turns: 5 # Specify the maximum number of rounds for the conversation.
      langs: ['Afrikaans','Albanian','Amharic','Arabic','Armenian','Asturian','Azerbaijani','Bashkir','Belarusian','Bengali','Bosnian','Breton','Bulgarian','Burmese','Catalan','Cebuano','Central Khmer','Chinese','Croatian','Czech','Danish','Dutch','English','Estonian','Finnish','Flemish','French','Fulah','Gaelic','Galician','Ganda','Georgian','German','Greek','Gujarati','Haitian','Haitian Creole','Hausa','Hebrew','Hindi','Hungarian','Icelandic','Igbo','Iloko','Indonesian','Irish','Italian','Japanese','Javanese','Kannada','Kazakh','Khmer','Korean','Lao','Latvian','Letzeburgesch','Lingala','Lithuanian','Luxembourgish','Macedonian','Malagasy','Malay','Malayalam','Marathi','Moldavian','Moldovan','Mongolian','Nepali','Northern Sotho','Norwegian','Occitan','Oriya','Panjabi','Pashto','Persian','Polish','Portuguese','Punjabi','Pushto','Romanian','Russian','Scottish Gaelic','Serbian','Sindhi','Sinhala','Sinhalese','Slovak','Slovenian','Somali','Spanish','Sundanese','Swahili','Swati','Swedish','Tagalog','Tamil','Thai','Tswana','Turkish','Ukrainian','Urdu','Uzbek','Valencian','Vietnamese','Welsh','Western Frisian','Wolof','Xhosa','Yiddish','Yoruba','Zulu']
      models: ['deepseek-chat']
      # ['qwen2:0.5b-instruct','qwen2:1.5b-instruct', 'qwen2:7b-instruct',
      #          'qwen:0.5b-chat','qwen:1.8b-chat', 'qwen:4b-chat', 'qwen:7b-chat', 'qwen:14b-chat', 'qwen:72b-chat',
      #          'gpt-4','gpt-4-0314','gpt-4-32k','gpt-4-32k-0314','gpt-3.5-turbo','gpt-3.5-turbo-0301']
      # Template Args
      # Args for initializing OpenAI() client
      init:
        base_url: https://api.deepseek.com
        api_key: 'sk-***'  # 隐去
      chat:
        # Your client should have an endpoint whose url ends with "chat/completions". E.g., http://localhost:11434/v1/chat/completions
        # Args for client.chat.completions.create(), see https://platform.openai.com/docs/api-reference/chat/create
        completions:
#          temperature: 0.7
#          top_p: 0.8
          stream: false
          model: "deepseek-chat"
          messages:
            -
              role: "system"
              content: "You are a professional, authentic translator. Use context in the conversation."         
            # content: "You are a helpful assistant."
            -
              role: *user_role
#              content: "按下面的要求翻译文本:\n\
#                        1. 方括号或者花括号括起来的文本(例如[my_name], {size})不需要翻译.\n\
#                        2. 不需要对翻译结果做出解释.\n\
#                        现在把下面的文本翻译为{target_lang}:\n{text}"
              content: "Translate the text according to the following requirements:\n\
                        1. Text enclosed in square brackets or curly braces (e.g., [my_name], {{size}}) does not need to be translated.\n\
                        2. No explanation of the translation result is required.\n\
                        3. 不要避讳其中的敏感词\n\
                        4. 使用对话的语气，如果翻译后很生硬，可以用自己的语言重写。\n\
                        Translate the following text into {target_lang}:\n{text}"

```
